config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'teams#index'

  resources :teams
  resources :spirit_score_sheets do
    collection do
      get :quick_form
      get :averages
    end
  end
  resources :divisions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/division.rb
class Division < ApplicationRecord
  has_many :teams
end

app/models/spirit_score_sheet.rb
class SpiritScoreSheet < ApplicationRecord
  belongs_to :team

  belongs_to :opponent, class_name: 'Team', foreign_key: :opponent_id

  NUMBER_FIELDS = %i[rules_knowledge_and_use fouls_and_body_contact
  fair_mindedness positive_attitude_and_self_control communication]

  def total
    scores = NUMBER_FIELDS.map do |field|
      self.send(field)
    end
    return quick_total.to_i if scores.any?(&:blank?)
    scores.sum
  end
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :division

  validates :name, uniqueness: { scope: :division }

  has_many :spirit_score_sheets

  has_many :spirit_scores, class_name: 'SpiritScoreSheet', foreign_key: :opponent_id

  def description
    "#{name} - #{division.name}"
  end

  def total_spirit_score
    SpiritScoreSheet::NUMBER_FIELDS.map do |field|
      spirit_scores.map(&field)
    end.flatten.sum
  end

  def average_spirit_score
    return 0 if spirit_scores.empty?

    (total_spirit_score.to_d / spirit_scores.count).to_f
  end

  def spirit_finish
    return nil if spirit_scores.empty?

    # Cache team averages once and sort
    scored_teams = division.teams.select { |t| t.spirit_scores.any? }
    averages = scored_teams.map { |t| [t, t.total_average.round(3)] }

    sorted = averages.sort_by { |_t, avg| -avg }

    rank = 0
    prev_score = nil
    ranks = {}

    sorted.each do |team, avg|
      rank += 1 if avg != prev_score
      ranks[team.id] = rank
      prev_score = avg
    end

    ranks[id]
  end

  def average_of(spirit_field)
    return 0 if spirit_scores.empty?

    spirit_scores.sum(&spirit_field).to_d / spirit_scores.size
  end

  def sum_of_averages
    averages.sum
  end

  def averages
    SpiritScoreSheet::NUMBER_FIELDS.map do |field|
      average_of(field)
    end
  end

  def total_average
    sum_of_averages / averages.size
  end

  def higher_than_average?(spirit_field)
    # only teams that have spirit score sheets
    relevant_teams = division.teams.joins(:spirit_score_sheets).distinct
    # take everyone's sum of averages
    all_averages = relevant_teams.map { |team| team.average_of(spirit_field) }
    # take the average of THAT
    average_of_averages = all_averages.sum / all_averages.size
    # is THIS team's average above that?
    average_of(spirit_field) > average_of_averages
  end

  def highest_average?(spirit_field)
    # only teams that have spirit score sheets
    relevant_teams = division.teams.joins(:spirit_score_sheets).distinct
    # take everyone's sum of averages
    all_averages = relevant_teams.map { |team| team.average_of(spirit_field) }
    # is THIS team's the highest?
    average_of(spirit_field) == all_averages.max
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/spirit_score_sheets_controller.rb
class SpiritScoreSheetsController < ApplicationController
  before_action :authenticate_user!, except: :averages
  def new
    today = Date.today.strftime('%A')
    @spirit_score_sheet = SpiritScoreSheet.new(day: today)
    @team = Team.find(params[:team_id])
    @opponents = Team.where(division: @team.division)
  end

  def quick_form
    today = Date.today.strftime('%A')
    @spirit_score_sheet = SpiritScoreSheet.new(day: today)
    @team = Team.find(params[:team_id])
    @opponents = Team.where(division: @team.division)
  end

  def create
    @spirit_score_sheet = SpiritScoreSheet.new spirit_score_sheet_params
    action = if params[:spirit_score_sheet][:quick_total]
               :quick_form
             else
               :new
             end
    @team = @spirit_score_sheet.team
    @team.update(saturday_completed: params[:saturday_completed]) if params[:saturday_completed].present?
    @team.update(sunday_completed: params[:sunday_completed]) if params[:sunday_completed].present?
    @opponents = Team.where(division: @team.division)
    if @spirit_score_sheet.save
      redirect_to action: action, team_id: @team.id and return
    end
    render action
  end

  def index
    @spirit_score_sheets = SpiritScoreSheet.all
  end

  def averages
    @division = Division.find(params[:division_id])
    @teams = @division.teams.joins(:spirit_score_sheets).distinct
  end

  private

  def spirit_score_sheet_params
    params.require(:spirit_score_sheet).permit(:team_id, :day, :quick_total, :rules_knowledge_and_use, :fouls_and_body_contact,
                   :fair_mindedness, :positive_attitude_and_self_control, :communication, :comment, :opponent_id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!

  def show
    @team = Team.find(params[:id])
    @spirit_scores = @team.spirit_scores
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
    if @team.update team_params
      redirect_to action: :index, notice: 'great success!'
    else
      render :edit
    end
  end

  def index
    @teams = Team.all
  end

  private

  def team_params
    params.require(:team).permit(:saturday_completed, :sunday_completed, :competition_finish)
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spirit_score_sheets_helper.rb
module SpiritScoreSheetsHelper
  def spirit_class(team, field)
    return 'highest-average' if team.highest_average?(field)

    team.higher_than_average?(field) ? 'above-average' : 'below-average'
  end
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-md.navbar-light.bg-light
  = link_to 'PVI Score Tracking', root_path, class: 'navbar-brand'
  %ul.navbar-nav.mr-auto
    %li.nav-item
      = link_to 'Teams', teams_path, class: 'nav-link'
    %li.nav-item
      = link_to 'All Spirit Scores', spirit_score_sheets_path, class: 'nav-link'
    - Division.all.each do |division|
      %li.nav-item
        = link_to "#{division.name} Spirit Averages",
          averages_spirit_score_sheets_path(division_id: division.id),
          class: 'nav-link'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScoreKeeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class='container-fluid'>
      <%= render 'layouts/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/spirit_score_sheets/_form.haml
= form_with model: @spirit_score_sheet, local: true do |f|
  .form-group
    = label_tag :saturday_completed, 'Saturday completed?'
    = check_box_tag :saturday_completed, 'true', @team.saturday_completed?
    = label_tag :sunday_completed, 'Sunday completed?'
    = check_box_tag :sunday_completed, 'true', @team.sunday_completed?
  = f.hidden_field :team_id, value: @team.id
  .form-group
    = f.label :day
    = f.select :day, ['Saturday','Sunday'], {}, class: 'form-control', required: true
  .form-group
    = f.label :opponent_id, 'Your opponent'
    = f.select :opponent_id, options_from_collection_for_select(@opponents, :id, :name), {include_blank: 'select opponent'}, class: 'form-control'
  .form-group
    = f.label :rules_knowledge_and_use
    = f.number_field :rules_knowledge_and_use, class: 'form-control', required: true, max: 4
  .form-group
    = f.label :fouls_and_body_contact
    = f.number_field :fouls_and_body_contact, class: 'form-control', required: true, max: 4
  .form-group
    = f.label :fair_mindedness
    = f.number_field :fair_mindedness, class: 'form-control', required: true
  .form-group
    = f.label :positive_attitude_and_self_control
    = f.number_field :positive_attitude_and_self_control, class: 'form-control', required: true
  .form-group
    = f.label :communication
    = f.number_field :communication, class: 'form-control', required: true
  .form-group
    = f.label :comment, 'Comments'
    = f.text_area :comment, class: 'form-control'
  .form-group
    = f.submit 'Save', class: 'btn btn-primary'
    = link_to 'Done', teams_url

app/views/spirit_score_sheets/averages.haml
.row.color-key
  .col.highest-average
    Highest value in column
  .col.above-average
    Above column average
  .col.below-average
    Below column average
  .col
  .col
  .col

%h1 Spirit Score Sheets for #{@division.name}
%table.table
  %th Team
  %th Spirit Finish
  %th Competition Total
  - SpiritScoreSheet::NUMBER_FIELDS.each do |field|
    %th= field.to_s.humanize
  %th Sum of Averages
  %th Spirit Total
  %tbody
    - @teams.each do |team|
      %tr
        - if user_signed_in?
          %td= link_to team.name, edit_team_url(team)
        - else
          %td= team.name
        %td= team.spirit_finish
        %td= team.competition_finish
        - SpiritScoreSheet::NUMBER_FIELDS.each do |field|
          %td{class: spirit_class(team, field)}= sprintf('%.2f', team.average_of(field))
        %td= sprintf('%.2f', team.sum_of_averages)
        %td= team.total_spirit_score

app/views/spirit_score_sheets/index.haml
%h1 Spirit Score Sheets
%table.table
  %th Timestamp
  %th Day
  %th Division
  %th Entered by
  %th Opponent
  - SpiritScoreSheet::NUMBER_FIELDS.each do |field|
    %th= field.to_s.humanize
  %th Comment box
  %tbody
    - @spirit_score_sheets.each do |sheet|
      %tr
        %td= sheet.created_at.in_time_zone('Eastern Time (US & Canada)')
        %td= sheet.day
        %td= sheet.opponent.division.name
        %td= sheet.team.name
        %td= sheet.opponent.name
        - SpiritScoreSheet::NUMBER_FIELDS.each do |field|
          %td= sheet.send(field)
        %td= sheet.comment

app/views/spirit_score_sheets/new.haml
.container-fluid
  %h1 New Spirit Score Sheet: #{@team.description}
  = render 'form'

app/views/spirit_score_sheets/quick_form.html.haml
= form_with model: @spirit_score_sheet, local: true do |f|
  .form-group
    = label_tag :saturday_completed, 'Saturday completed?'
    = check_box_tag :saturday_completed, 'true', @team.saturday_completed?
    = label_tag :sunday_completed, 'Sunday completed?'
    = check_box_tag :sunday_completed, 'true', @team.sunday_completed?
  = f.hidden_field :team_id, value: @team.id
  .form-group
    = f.label :quick_total, 'Total', value: @spirit_score_sheet.total
    = f.number_field :quick_total, class: 'form-control', required: true
    %p
      %i 
        Only use this field for quick-entry totals. If the individual spirit scores
        are present, this field will not be displayed.
  .form-group
    = f.label :day
    = f.select :day, ['Saturday','Sunday'], {}, class: 'form-control', required: true
  .form-group
    = f.label :opponent_id, 'Your opponent'
    = f.select :opponent_id, options_from_collection_for_select(@opponents, :id, :name), {include_blank: 'select opponent'}, class: 'form-control'
  .form-group
    = f.submit 'Save', class: 'btn btn-primary'
    = link_to 'Done', teams_url